language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
php:
  - 7.1
  - 7.2
  - nightly

env:
  - DEPENDENCIES=no
  - DEPENDENCIES=beta
  - DEPENDENCIES=low
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*

matrix:
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low

before_install:
  - composer self-update
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Disable xdebug, there is no use of it being enabled
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  # Prevent Travis throwing an out of memory error
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Test if we have a token for github as the project may hit the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest --prefer-stable update; else composer update; fi;

script:
  - composer validate-files
